### ISSUE TITLE
Run the official (publish-test.sh) script to appear 404

### ISSUE THREAD

**Issue by danyangzhu** [Netflix/atlas#1094]
![image](https://user-images.githubusercontent.com/47710976/67205880-3cb51f80-f443-11e9-93e4-b539a4235a18.png)
How to solve it?

**Comment by brharrington** [comment]
You need to run with the appropriate configuration:

https://github.com/Netflix/atlas/wiki/Getting-Started#running-demo-with-memory-storage

**Comment by danyangzhu** [comment]
I use the configuration in the attachment, Use your script or 404, can you help me see it?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"brharrington"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 晚上9:26
收件人:&nbsp;"Netflix/atlas"<atlas@noreply.github.com&gt;;
抄送:&nbsp;"Damn！"<863608687@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Netflix/atlas] Run the official (publish-test.sh) script to appear 404 (#1094)




You need to run with the appropriate configuration:
 
https://github.com/Netflix/atlas/wiki/Getting-Started#running-demo-with-memory-storage

**Comment by brharrington** [comment]
When running the Atlas server you need to specify the `memory.conf` file as directed in the documentation section I linked.

**Comment by danyangzhu** [comment]
I used the memory.conf on your link, but it is still 404. Is there another cluster version?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"brharrington"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 晚上9:26
收件人:&nbsp;"Netflix/atlas"<atlas@noreply.github.com&gt;;
抄送:&nbsp;"Damn！"<863608687@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Netflix/atlas] Run the official (publish-test.sh) script to appear 404 (#1094)




You need to run with the appropriate configuration:
 
https://github.com/Netflix/atlas/wiki/Getting-Started#running-demo-with-memory-storage

**Comment by danyangzhu** [comment]
I am fixing the problem now. I want to take a cluster version now. Do you have any information? Thank you


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"brharrington"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 晚上11:50
收件人:&nbsp;"Netflix/atlas"<atlas@noreply.github.com&gt;;
抄送:&nbsp;"Damn！"<863608687@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Netflix/atlas] Run the official (publish-test.sh) script to appear 404 (#1094)




When running the Atlas server you need to specify the memory.conf file as directed in the documentation section I linked.

**Comment by danyangzhu** [comment]
I tested Atlas，Single point write，Found that the efficiency is not high。Is there a way to write data in batches?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"brharrington"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 晚上11:50
收件人:&nbsp;"Netflix/atlas"<atlas@noreply.github.com&gt;;
抄送:&nbsp;"Damn！"<863608687@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Netflix/atlas] Run the official (publish-test.sh) script to appear 404 (#1094)




When running the Atlas server you need to specify the memory.conf file as directed in the documentation section I linked.

**Comment by brharrington** [comment]
The clustering we use internally is tied to some other internal infrastructure that is not open source at this time. Also, in talking with some other teams, the specific requirements for clustering have tended to vary a bit across users. For example, you can read about the approach Outlyer took using Atlas in this blog post:

https://medium.com/dataseries/why-not-to-build-a-time-series-database-e1e63a535357

By single point write, do you mean one request to the publish endpoint per data point? If you look at the publish format you can send many data points in a request. We typically do batches of around 10k. Depending on the use-case you could also create a custom publish endpoint and configure to use that for something more efficient than the default HTTP/JSON. We have done that in some cases.

What is the primary use-case you are going after? Atlas will probably take more work to make usable than some of the other options at this time. Our main focus is on internal use-cases and it is centrally hosted at Netflix. There is a lot to be desired in terms of usability for operators that we do not currently have the bandwidth to focus on since it isn't a pain point for us. The teams I'm aware of that are using it outside Netflix are similar to the Outlyer case where Atlas is a building block as part of their supported offering.

**Comment by danyangzhu** [comment]
Where is the release format of about 10,000 batch productions, can you give a link?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"brharrington"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月23日(星期三) 晚上9:47
收件人:&nbsp;"Netflix/atlas"<atlas@noreply.github.com&gt;;
抄送:&nbsp;"Damn！"<863608687@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Netflix/atlas] Run the official (publish-test.sh) script to appear 404 (#1094)




The clustering we use internally is tied to some other internal infrastructure that is not open source at this time. Also, in talking with some other teams, the specific requirements for clustering have tended to vary a bit across users. For example, you can read about the approach Outlyer took using Atlas in this blog post:
 
https://medium.com/dataseries/why-not-to-build-a-time-series-database-e1e63a535357
 
By single point write, do you mean one request to the publish endpoint per data point? If you look at the publish format you can send many data points in a request. We typically do batches of around 10k. Depending on the use-case you could also create a custom publish endpoint and configure to use that for something more efficient than the default HTTP/JSON. We have done that in some cases.
 
What is the primary use-case you are going after? Atlas will probably take more work to make usable than some of the other options at this time. Our main focus is on internal use-cases and it is centrally hosted at Netflix. There is a lot to be desired in terms of usability for operators that we do not currently have the bandwidth to focus on since it isn't a pain point for us. The teams I'm aware of that are using it outside Netflix are similar to the Outlyer case where Atlas is a building block as part of their supported offering.

**Comment by brharrington** [comment]
Not sure I follow your question correctly. If you look at the `publish-test.sh` example the payload has a `metrics` field which is a list of data points. The example for that script is sending two data points.
