### ISSUE TITLE
Compare to current alternatives?

### ISSUE THREAD

**Issue by elgalu** [Netflix/atlas#1198]
Would it be possible to compare to current alternatives like https://github.com/influxdata/influxdb or maybe even https://github.com/apache/druid

**Comment by brharrington** [comment]
It has been a while since I have looked at Influx or Prometheus deeply enough to provide an up to date comparison. All three focus solely on time series. Prometheus and Influx will generally be easier to use as is and have much bigger communities with better support. Atlas is mainly developed for our use-cases at Netflix. There have been a few external adopters, but they have been groups like us that are then using Atlas as a component in a larger setup with a lot of other tooling built around it. So ease of initial adoption will likely be quite a bit higher with Atlas. As an example see this [blog post from Outlyer](https://medium.com/dataseries/why-not-to-build-a-time-series-database-e1e63a535357). One of the initial goals was to open source the full ecosystem around Atlas, but that has proven to be difficult given the amount to which those systems are tied to internal Netflix conventions or systems. It becomes a big effort and thus far the focus has been on other priorities. 

Druid can be used for time series, but is a bit broader than that. It is also used at Netflix for a wide variety of use-cases and we have also experimented with using Druid storage with the Atlas query layer to ease integration with other tooling built around Atlas. That said, Druid is mostly used as a more general purpose analytics database for application specific use-cases. This means there is more work for the user similar to using a traditional SQL DB (defining a schema, figuring out optimal ways to query, retention policies, etc). Atlas is used for time series specifically and primarily focused on operational use-cases. Druid has more flexibility, but there is some operational risk and complexity that comes with it.
