### ISSUE TITLE
use different color schemes error images

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#19]
It has been proposed that the color scheme for the error images could be used to indicate whether it is a user error or some problem with the server.

**Comment by svachalek** [comment]
Colors would be good, but some clear templating might be more important. Something along the lines of:

  There was an internal error in the Atlas server, please report this message to the support team: [internal error message]

or 

  The load on the Atlas server is currently too high. Please wait a few minutes before resubmitting this query, or contact the support team for further assistance.

or 

  Query was invalid. Please correct the query and resubmit: [query error message]

or 

  Your query cannot be processed as written due to the size of the result set. Please consult the FAQ for suggested ways to reduce the size of the result set.  [detailed error]

**Comment by brharrington** [comment]
From @nathfisher , add some sort of code that could be used to lookup the error information.

**Comment by zimmermatt** [comment]
Good suggestions @svachalek and @nathfisher.  The color coding change originally conceived for this issue is a relatively quick win, so I've split out the suggestions you made to a separate issue for later implementation.
