### ISSUE TITLE
Information on block size

### ISSUE THREAD

**Issue by drax68** [Netflix/atlas#246]
Hi, I need some information regarding block size.
What is the meaning of block size? What is a drawbacks of using small number of blocks where each has a big size instead of larger number of blocks where each block has a small size (in context of in-memory storage)?

**Comment by brharrington** [comment]
We experimented with it some a long time ago, but have typically used 1 hour for all of our current use-cases. Overview on some of the impacts:

**Data Retention**

Our data model is kind of like RRD in that there is a fixed number of blocks and older data will drop out when the window is filled. The block size is unit of rotation. So if you have six 1-hour blocks the amount of data available would be 5 to 6 hours. At the hour boundary the old block will go away and a new block will start filling.  

**Churn**

For our use-cases a given time series is often short lived. As one example just consider metrics for a given instance. At Netflix instances have become more and more short lived because:

* Our deployment model is to replace with new instances rather than update existing instances.
* Frequency of deployments continues to increase, many of the apps that our the biggest metrics producers deploy at least once a week and usually more often
* Increased use of auto-scaling so the sizes of clusters varies through the day

 So if your block size is large and the time series is short lived, then you are wasting a lot of space per time series because it will only have data for a narrow window.

**Batching and Compression**

The current block that is being filled is a simple array which is fast to update. After an hour boundary has passed and older data will no longer be accepted the historical block is now effectively immutable. So at this time we can see if we can compress it to reduce the memory overhead further. 

Also, for writing to persistence we write the completed blocks. So the block size becomes the level of batching for data flowing into the longer term storage. However, that also means the block size impacts the delay to get data to storage since data cannot be written out until the block it is apart of is complete.
