### ISSUE TITLE
Production Setup

### ISSUE THREAD

**Issue by taviLaies** [Netflix/atlas#276]
Hello,

Besides memory is or will there there be any other storage option available in 1.4 or 1.5?
I would like to have the same setup described here https://camo.githubusercontent.com/57ddedea3c60f776f5634474e70da232b64efee1/687474703a2f2f6e6574666c69782e6769746875622e696f2f61746c61732f696d616765732f77696b692f61746c61735f73746f726167655f61745f6e6574666c69782e737667
obviously the retentions will be different - we have a smaller volume. We would probably be able to keep 1w of data in memory.
Is EMR in the diagram used to roll up to coarser time units? Any other options for that? Ideally I don't want to deal with that at this stage, I think with our volume we should be okay with a simple rollup algorithm running directly on the S3 objects.

I can't find any documentation at all for this kind of setup.

More context on my project:

We are currently using spring-boot and metrics3 directly to collect metrics. metrics3 forwards them to Graphite. We are moving to Amazon ECS and autoscaling is increasingly being used so the fact that we have the instanceId(containerID) in the metric names is not a very good match for Whisper.

Now I'm looking to migrate that to spring-cloud-netflix with Spectator and Atlas. In order to be able to run Atlas in production I need to be able to also store and make historical data available.

Thank you

**Comment by brharrington** [comment]
> Besides memory is or will there there be any other storage option available in 1.4 or 1.5?

For 1.4 it will only get bug fixes at this point. For 1.5, there is no plan to support storage that serves from a location other than memory, but it should have the portion that loads from s3 merged. So it should be relatively easy to have it backed by a persistent source so it can be recovered.

1.5 is currently planned to be released by end of Q1 2016.

> Is EMR in the diagram used to roll up to coarser time units?

We use EMR for a lot of processing. In terms of what we keep in memory for quick serving we don't consolidate (rollup to coarser time granularity) though we have in the past. One of the main uses we have is doing time shifts like day over day and week over week to get a baseline for comparison. The consolidated datapoints made it difficult to reason about how the current behavior really relates to the past behavior.

The rollups we do now are for the set of tags available. For example, in the `< 16d ago` cluster we drop the instance dimension for almost all metrics which greatly reduces the overall volume. Due to auto-scaling and frequent deployments, instances are short lived and looking at a graph over several weeks or doing a time shift is useful for the aggregate at the cluster level, but not for the individual nodes. 

We also keep the data long term in hive and we do create a copy that is rolled to daily datapoints to make it more efficient for trending queries over a long time period.

> I can't find any documentation at all for this kind of setup.

Documentation is something we know needs to be improved and plan to make progress on that this quarter. One of the reasons this has been slow to come out is that some of the internal tooling we rely on heavily for this setup isn't open source.

There is also a todo item for documenting how much data can be stored on a given node with a specific configuration. Like most data systems though things like number of metrics depends a lot on the data characteristics.

**Comment by taviLaies** [comment]
K, so there will be support for backing up the in-memory data to S3. Any idea how the recovery process will look like?
What about the redundant setup? Will all the parts be available in 1.5 to build the architecture you describe describe where a "Publish" cluster handles sharding and replication?

**Comment by brharrington** [comment]
> Any idea how the recovery process will look like?

We treat recovery then is the same as deploying a new version. In general, we don't trust processes that are not run regularly. So there isn't a special recovery setup. When the process comes up and while running it will check and keep itself in sync with the S3 copy.

> Will all the parts be available in 1.5 to build the architecture you describe describe where a "Publish" cluster handles sharding and replication?

That is the current plan.
