### ISSUE TITLE
unknown world ':percentiles'

### ISSUE THREAD

**Issue by krutsko** [Netflix/atlas#345]
I'm using Spectator PercentileTimer and try to query Atlas as described here https://github.com/Netflix/atlas/wiki/math-percentiles

My query: 
http://localhost:7101/api/v1/graph?q=name,http.server.requestDuration,:eq,(,75,99,),:percentiles

Result: 
IllegalArgumentException: unknown world ':percentiles'

Atlas version: 1.4.6

**Comment by matschaffer** [comment]
Looks like percentiles was added in 1.5.0-rc.4

```console
❯ git blame ./atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala | grep Percentiles
66d13206 (Brian Harrington 2016-01-17 07:40:37 -0800  52)     Percentiles,
66d13206 (Brian Harrington 2016-01-17 07:40:37 -0800 656)   case object Percentiles extends SimpleWord {
66d13206 (Brian Harrington 2016-01-17 07:40:37 -0800 677)         MathExpr.Percentiles(expr, pcts) :: stack

~/code/atlas master
❯ git tag --contains 66d13206
v1.5.0-rc.4
v1.5.0-rc.5
```

**Comment by brharrington** [comment]
Yes, as @matschaffer mentioned it was added in a later version. Several have mentioned some confusion because the docs don't map well to a particular version. In the short-term I'll add a comment on the reference page for percentiles to note the version.

We'll probably move off of github wiki when I get the time and move to something where we can have versioned docs (and search). Currently we are experimenting with [mkdocs for spectator](http://netflix.github.io/spectator/en/latest/).
