### ISSUE TITLE
Feature Request: Sort Graph Legend

### ISSUE THREAD

**Issue by csanden** [Netflix/atlas#349]
## Summary
Given a query which results in multiple lines, it would be nice if there was an option to sort the legend by a summary statistic, i.e., sort the legend by max, min, avg, etc. 

## Example
Imagine we want to identify the node with the highest latency. In this example, it would be nice if we could sort the legend by max value and have the first entry in the legend be the node with the highest latency.

**Comment by brharrington** [comment]
I want to get some feedback on how this would work. Right now the legend is ordered based on the order on the stack and for expressions that have multiple results (group by) sorted by the legend text. The reason for this is to make it easy for someone to understand where an expression will show up in the legend.

**Option 1**

Consider a common alert visualization:

```
http://localhost:7101/api/v1/graph?s=e-1d&q=
  120e3,threshold,:legend,
  name,sps,:eq,(,nf.cluster,),:by,:dup,
  :max,120e3,:gt,30,:alpha,:vspan,trigger,:legend,:swap,
  $nf.cluster,:legend
```

![alert-viz](https://cloud.githubusercontent.com/assets/1289028/14788619/9655911e-0abd-11e6-8488-82051903e941.png)

For this type of visualization, I think it is desirable to have the threshold and trigger lines pinned to the top of the legend. However, this would not be true if the legend for a given axis was sorted by stat like max. This would imply we would need to do the sort per expression, something like:

```
name,sps,:eq,(,nf.cluster,),:by,max,:rsort
```

For now I'm assuming `:sort` and `:rsort` (reverse sort) that takes one of the [named stats](https://github.com/Netflix/atlas/wiki/filter-stat#summary). Probably also allow a value like `legend` so that the current default mode could be explicit.

**Option 2**

If we only allow sorting by expression, then a sequence of expressions that cannot be represented as a group by cannot be sorted. Example:

```
http://localhost:7101/api/v1/graph?s=e-1d&q=
  name,sps,:eq,:sum,1e3,:div,
  name,requestsPerSecond,:eq
```

![lines](https://cloud.githubusercontent.com/assets/1289028/14789031/925592ec-0abf-11e6-9f5d-2a7cf3b3af9e.png)

This would imply specifying the sort at a higher level like one of the url parameters for an axis.

```
&sort.0=max
```

**Option 3**

Allow both. I can argue for both option 1 and option 2 behavior, but I'm not sure how it would work to support both. Typically we have tried to follow a pattern where the most specific setting would take precedence, e.g. a [line style](https://github.com/Netflix/atlas/wiki/style-ls) in the expression will override the url param `&stack=1`. This case is a bit more difficult because the more specific setting cannot win without breaking the more general setting for other expressions.

So what should the behavior of something like this be:

```
http://localhost:7101/api/v1/graph?s=e-1d&sort=max&q=
  name,sps,:eq,:sum,(,nf.cluster,),:by,1e3,:div,max,:rsort,
  name,requestsPerSecond,:eq
```

I feel like silently picking either would be confusing so it should probably add a warning to the chart. Other than that I would like to prefer the most specific option. So I guess I would suggest if any sub-expression is explicitly sorted it disables the sort setting on the axis (with warning to user).

Thoughts? cc @tregoning @svachalek

**Comment by brharrington** [comment]
Added in #350.
