### ISSUE TITLE
Performance degrades over time

### ISSUE THREAD

**Issue by briangann** [Netflix/atlas#435]
I've noticed on a standalone cluster (using tip of tree) that the atlas process performance degrades over time.  The main indicator is the "rebuilding index", which incrementally increases in time.

Here's the setup:

Server with 16GB ram, startup params specify 12GB
Roughly 1 million metrics reported by index (retaining 3 hours at 60 step)
index rebuild time set to 30 seconds

The index rebuild time when "full" is around 15 seconds. Leaving this server up ingesting data for 24 hours, the index rebuild time is 7 minutes, and the queries are very slow or fail/timeout.

What is the recommended "size" for a standalone atlas server?

Is there a way to view the Spectator global registry metrics?

What memory size would be good for a clustered/sharded solution (I'm seeing similar degradation behavior with a 5-node 8GB cluster sharding implementation)

Thanks!

Brian

**Comment by brharrington** [comment]
My guess from what your describing is that GC is becoming a problem. What are the JVM parameters?

We typically run using G1 with a recent java 8 build (there are some known G1 issues on older versions, e.g., #81). CMS is prone to fragmentation and we have generally avoided it. In most cases we were better off using the old parallel collector than CMS prior to G1.

We typically run on r3.2xlarge instances assuming at most 2M time series per instance with 6h window and 60s step (we alert if the index size hits 2M and we can get up to 2.5 to 3 before major problems with this configuration depending on data characteristics). JVM params like:

```
java \
  -XX:+PreserveFramePointer \
  -Xss1024k \
  -XX:MetaspaceSize=256m \
  -XX:MaxMetaspaceSize=256m \
  -XX:+UseG1GC \
  -XX:StringTableSize=1000003 \
  -Xms52g \
  -Xmx52g \
  -XX:+HeapDumpOnOutOfMemoryError \
  -verbosegc \
  -verbose:sizes \
  -XX:+DisableExplicitGC \
  -XX:+PrintGCDetails \
  -XX:+PrintGCDateStamps \
  -Xloggc:/logs/atlas/gc.log \
  ...
```

A number of those are just for getting diagnostic information. Here is some overview on why we use some of the settings:

* `-XX:+PreserveFramePointer`: better [flame graphs](http://techblog.netflix.com/2015/07/java-in-flames.html)
* `-XX:MetaspaceSize`: avoid full GC due to metaspace, see #81
* `-XX:+UseG1GC`: generally works best for us when using recent java 8 builds, CMS is prone to fragmentation and we generally avoid it
* `-XX:StringTableSize=1000003`: we use string interning heavily to reduce memory for tags, if the table fills up the intern calls can get really slow
* `-Xms52g`, `-Xmx52g`: pin the heap size
* others: mostly debugging and things like GC logs

There are a few other configurations, but that is the main one we use. We haven't done a whole lot of testing recently on varying those or using other heap sizes. Note, data characteristics matter quite a bit, so these settings have been tuned for the data patterns we have at Netflix. In artificial tests we can get much more data using the same config with more optimal data patterns or less with some patterns.

I started setting up a basic [load test](https://github.com/brharrington/atlas-load-test) to make it easier to verify a number of configurations for both finding regressions and creating reasonable docs on recommended sizing and configuration, but don't have a lot of time to spend on it right now.

> Is there a way to view the Spectator global registry metrics?

There are a few ways to view them. In our internal setup they get reported to an Atlas cluster. There is also a simple [admin component](https://github.com/Netflix/iep/blob/master/iep-admin/src/main/java/com/netflix/iep/admin/endpoints/SpectatorEndpoint.java) we add on a number of our services when running them to get some additional debugging information. You can also configure a [registry](http://netflix.github.io/spectator/en/latest/registry/metrics3/) to send them to JMX if that is preferable.

**Comment by briangann** [comment]
Out setup is really simple (looks like the GC is the likely culprit, I did see a GC error in the logs at one point).  I'll spin it up with your parameters adjusted for a 16GB box and 3hours and see how it holds up.
I'll check out the spectator admin component also, I'm not familiar with spectator at all.

Sounds like the formula is ballparked around 4GB ram per million metrics per hour of retention, If so, I should be able to handle about 3 hours safely only a 16GB system (with jvm pinned to 12gb).

Many thanks for the reply!

Brian

Here's our setup:

Running on an m4.xlarge (4vCPU, 16GB RAM)

JDK: jdk-8u91-linux-x64

Startup with:

java -Xmx12g -Xms12g \
 -Dcom.sun.management.jmxremote.port=9999 \
 -Dcom.sun.management.jmxremote.authenticate=false \
 -Dcom.sun.management.jmxremote.ssl=false \
 -Dlog4j.configurationFile=/usr/local/atlas/log4j2.xml \
 -XshowSettings:all \
 -jar /usr/local/atlas/atlas.jar /usr/local/atlas/atlas.conf

Here are some errors from old logs:

atlas: #
atlas: # A fatal error has been detected by the Java Runtime Environment:
atlas: #
atlas: #  SIGBUS (0x7) at pc=0x00007fe1f66578ce, pid=15045, tid=140607043139328
atlas: #
atlas: # JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
atlas: # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.91-b14 mixed mode linux-amd64 compressed oops)
atlas: # Problematic frame:
atlas: # C  [libc.so.6+0x14e8ce]  __memmove_ssse3_back+0xbfe

and a GC OOM:

atlas: 2016-08-09T07:32:02.708 ERROR [atlas-akka.actor.default-dispatcher-3279] akka.event.slf4j.Slf4jLogger$$anonfun$receive$1$$anonfun$applyOrElse$1: Uncaught error from thread [atlas-akka.actor.default-dispatcher-3265] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
atlas: java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by brharrington** [comment]
Based on the volume you mention, I would also recommend being explicit about the string table size (`-XX:StringTableSize=1000003`).

**Comment by briangann** [comment]
Reporting back - the standalone setup has been running flawlessly for 24hrs now, no degradation at all.  It's holding 3hrs of metrics, with an index hovering around 1.2million.

Many thanks!
