### ISSUE TITLE
consider supporting a notion of TTL for gauges

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#559]
The main use-case is handling some gauges that may be reported from distributed source and for whatever reason cannot match the step interval for the storage.

/cc @mohitvora @drather19

**Comment by brharrington** [comment]
**Use-case:**

The particular use-case is a gauge value that effectively comes from an event that can arrive at any instance of a stateless cluster and is less frequent then the step size. Right now the user maintains a separate data store to keep track of these values and then read and report them regularly to Atlas. They would prefer to remove this intermediate storage layer.

**Alternatives:**

* Keep state and maintain TTL locally on reporting instances. Doesn't work in this case because they have a stateless cluster. There is no clear way to aggregate if only one receives an update for a given time and multiple are reporting. For example, with counters it is not really a problem because the sum aggregate is correct. 

**Concerns:**

* Atlas is not a general purpose datastore and should not be conflated with complex storage tuning. Need to be clear on exactly what use-case we are trying to solve and why it is appropriate for a time series database.
* We have generally tried to be more accurate over time with what we actually know. In this case the TTL is basically covering up a window where we really don't know what is going on and have no measurements. Debugging this can be difficult because it is all transient internal state.
* The max TTL should be bounded.
    * Storage is in memory, we don't want to keep around a bunch of items around for a long period.
    * During a deployment or if an instance is lost the TTL state will be lost or briefly inconsistent between mirrors.
    * From an Atlas perspective max TTL should be as short as possible, assume target of 1h for now. Might depend on settings, but for current internal setups no more than 4h to avoid problems with deployment sanity checks.
    * From user perspective, if it is too short, then it might not be usable. Where do we draw the line? 
* How is TTL conveyed or set?
    * Per metric? There is not a good way to set it. It could be something like `atlas.ttl` tag, but a change to the TTL would change the sharding for that metric. A custom field would require a lot of changes to many components.
    * Per deployment? We could just fix the TTL for a given deployment. Would likely still need to have it be explicitly enabled either via something like `atlas.ttl` or perhaps a different `atlas.dstype`.  For example, just set it to 1h if TTL is enabled. Avoids complexity of specifying TTL and may not preclude it in the future if needed.
* Can a TTL be cancelled early? How would this work? In general we don't really want to introduce control options on the publishing. Less of a concern with small TTL as waiting for it to expire is not that long.
* What is the mechanism? Currently data flowing in causes a given data point to get pushed down after normalization. Something will have to know how to carry forward the values using TTL.

**Comment by mohitvora** [comment]
@drather19,
Please suggest whether a 1 hour TTL will work.

@brharrington, 
Our current use case, assumes per metric TTL. @drather19 please suggest if all TTLs can be set to 1 hour. Another option is having one of N possible values. Can the sharding exclude a particular tag? Are there any other use cases for some tags not participating in the sharding?

At the point where a new value is seen for a certain metric (before TTL expires) the expectation would be that the new value takes precedence and 'overwrites' the old one. Other than that, we've not come across a need for cancelling the TTL.

**Comment by brharrington** [comment]
> Are there any other use cases for some tags not participating in the sharding?

No, a metric is identified by the distinct set of tags and they aren't typically used for control type settings. It generally seems pretty hacky to me.

@dmuino also brought up the option that maybe our team supports some option for this, but keep it separate from the Atlas backend. My concern is that would basically be us building something similar to what you already have. It might be worthwhile syncing on what the main pain points you have with the existing option other than just having to spend time running/supporting it. The primary benefit is it could use a storage layer that is actually designed for customization and setting TTLs.

**Comment by drather19** [comment]
Regarding TTL lengths, we have some pathological cases with 25 hour TTLs. We may want to revisit those particular cases and treat them differently if we end up with a much smaller max TTL. However, it would present a departure from what our downstream users are used to relying on.

I don't think forcing all TTL's to the same value would work too well for downstream users. There's some expectation that the TTL is tied to the context in which that gauge is being used/reported, so we'd likely want this to be settable per-metric.

The idea of baking this into the Atlas backend sounded interesting when @brharrington mentioned it since there was a possibility of it being sympathetic with the existing backend. However, if glomming it into the backend forces a departure from existing design principles/assumptions, writing this as a separate service seems reasonable.

Having the Atlas folks look into this would be nice in that it's likely a useful feature for other Atlas users. Even if this kicks back to our team, we'd likely want to discuss further so the service is more readily available to other teams.

Lastly, we'd also briefly discussed (but abandoned at the time) the notion of baking this in at the query level, but would require some unpleasant gymnastics to fetch backwards up to a max TTL length of time to find a gauge reading to apply to the actual relevant time window. Just including it here for more context.

**Comment by brharrington** [comment]
Will be done with separate internal service.
