### ISSUE TITLE
Query layer questions

### ISSUE THREAD

**Issue by davecromberge** [Netflix/atlas#622]
In this [presentation](http://netflix.github.io/atlas/slides/atlas_overview.pdf) by @brharrington, reference is made to a query layer - specifically "query blending".  I understand this to refer to merging results from queries that span storage subsystems, where historical data may have been rolled up/aggregated.  

I would like to know more details about how this layer works.  Does it use the Atlas library interpreter on incoming queries to determine the time range, and use this to route queries to appropriate backend storages?  

Consider an active STS for the last 6 hours(with no rollups) and a historical STS for the < 7 days with rollups.  Would a query spanning the last 12 hours rollup 6 hours from the active STS and take the rest from the historical STS?  I assume that the historical STS would only get new data periodically from the EMR layer and would not have the latest, say 1 hour of data.  

I would appreciate a little more detail on how the query layer is able to arrange itself hierarchically and blend results from various storage systems.

**Comment by brharrington** [comment]
Responses inline:

> Does it use the Atlas library interpreter on incoming queries to determine the time range, and use this to route queries to appropriate backend storages?

Yes it will figure out the time range based on the start and end parameters and then map that to the underlying storage tiers.

> Would a query spanning the last 12 hours rollup 6 hours from the active STS and take the rest from the historical STS?

Both tiers will evaluate the query. If the dimension that was rolled up is relevant to the query, then you would get no results from the historical tier since it doesn't have the information. For queries where the rollup dimension is not important then it would blend both. For example lets say we have cpu and rollup the node dimension for the historical tier. Assuming the nodes have been around the entire time, the following would show data for the last 6h because the node is needed to answer the query:

```
name,cpu,:eq,node,i-1234,:eq,:and,:avg
name,cpu,:eq,(,node,),:by
```

If the node is not relevant, then it would show the full 12h, e.g.:

```
name,cpu,:eq,:avg
name,cpu,:eq,:avg,(,zone,),:by
```

Note that the set of time series resulting for these queries will be the same from both tiers. So we just need to match the corresponding entries.

> I assume that the historical STS would only get new data periodically from the EMR layer and would not have the latest, say 1 hour of data.

Correct. In our case we flush data into s3 every hour. We'll process that data to generate the files loaded by the historical tier. There is a typical delay of about 2h for us, the 6h window gives us enough overlap we can deal with minor issues without any gaps showing up for users.

**Comment by davecromberge** [comment]
Thank you for your detailed explanation @brharrington, it is more clear how it fits together.
I'm curious about the flushing, there does not seem to be any way to tell that a block has been completed, in the block store.  Does your persistence layer use the streaming interface and then periodically flush the resulting chunk, or do you use the fetch API to get a completed block every hour?

**Comment by brharrington** [comment]
> I'm curious about the flushing, there does not seem to be any way to tell that a block has been completed, in the block store.

It is time based. We have a block that we are currently filling and so we know when the time window for it closes. One difference between Atlas and many other systems is that we restrict how old data can be when flowing into the system. Part of the reason is we need to have guarantees around when data will be complete and actionable for alerts and after that time we do not want it to change. 

> Does your persistence layer use the streaming interface and then periodically flush the resulting chunk, or do you use the fetch API to get a completed block every hour?

There is an internal api that we include when running the 6h tier that currently pushes the data off to a persistence cluster. We are experimenting with changing that to a pull. It is a bit different than graph/fetch in that the data is the compressed blocks, so it isn't a format that is very convenient for an end user. Essentially though, you can think of it kind of like a cron job that a little bit after the close of the hour, for use we typically do it at 10min after, will flush the compressed blocks from the last hour to persistence. The persistence cluster has some additional logic about making sure it got data from all shards, they completed writing, etc.

**Comment by davecromberge** [comment]
I think it's been mentioned in some previous issues that you plan to release some of the surrounding infrastructure, is that still on your roadmap?  Thanks for the above explanation, it helps a lot with understanding the Atlas ecosystem - the diagram on the wiki hints to their existence but it's very useful to figure out how they work.

**Comment by brharrington** [comment]
> I think it's been mentioned in some previous issues that you plan to release some of the surrounding infrastructure, is that still on your roadmap?

Yes and there should be some progress on that in the coming months. The main limitation is time, our team is pretty lean and internal priorities come first. A number of the changes needed are to separate it from internal assumptions and dependencies, but this is less useful internally. In some cases it is also beneficial internally in the longer term as it gives us more flexibility. However, short term it isn't a pressing internal need. To that end I'm trying to avoid a big code dump with overly aspirational refactoring that we aren't able to use internally for a prolonged period. That was done with a number of NetflixOSS projects, but the typical end result is that the internal version diverges over time. Though it is taking time we are actually using the system internally as we open source it.

**Comment by davecromberge** [comment]
It makes sense, thanks for putting the time into answering my questions.
