### ISSUE TITLE
Mirrored short term storage

### ISSUE THREAD

**Issue by davecromberge** [Netflix/atlas#649]
I have a question about the short term storage tier. My understanding of the Netflix deployment is that data is mirrored across AZs and that instances fall under auto scaling groups.

I have tried to replicate some of the ideas presented in the documentation and videos but have some specific conerns about mirrors:
- Do the number of instances in one mirrored ASG match that of its corresponding mirror?

- Also, if an aggregation function is applied to the instances comprising one mirror, and then to the other, how are differences reconciled? To be more concrete, consider mirror 1 with 6 instances in the ASG and mirror 2 with 5 instances. Mirror 2 has received less of the data because of slower processing. How would an average with two different values be reconciled? Does blending values necessitate getting access to the underlying values and merging, before applying any query aggregates?

As always, I would be grateful for insights on how these situations are resolved at Netflix. I am considering seeing mirrors at equals and just querying one, and not blending when querying STS.

**Comment by brharrington** [comment]
> My understanding of the Netflix deployment is that data is mirrored across AZs and that instances fall under auto scaling groups.

That is still partially true. We deploy in that manner for deployments that follow a regional island model and need to be able to handle a zone failure. Originally all of our deployments followed this pattern.

About 2y ago we started switching most of our deployments for Atlas to a global model where we run multiple regions, each region being a replica, and tee the data from clients to each replica. This change was made predominantly because more and more of our internal query use-cases were global and needed data from all regions.

We do have the data sharded across instances in an ASG or set of ASGs.

> Do the number of instances in one mirrored ASG match that of its corresponding mirror?

For us they typically do, but do not have to. When we resize for example they will temporarily be different. In the past we have experimented with some techniques that did require them to be the same size. One example is speculative execution that only worked if the mirrors was the same size because it needed to know which instances in the mirror ASGs had the same data to pick the first of those that succeeded.

In our current usage we typically only send queries to one mirror at a time and the ASG sizes do not have to match. The primary reasons are:

* We typically do corrective merge of the data in hadoop for the longer term storage. That means each short term mirror could have slightly different data if there is a failure going to one or the other. Queries using both mirrors or alternating can result in minor variations in the chart when a user refreshes. We found that caused more confusion than it was worth.
* Sending queries to both mirrors simultaneously increases the probability that both mirrors will be impacted at the same time. For example, we have had bugs were certain queries resulted in bad behavior causing the mirror to fail. At one time we also did a query time corrective merge for short term storage, but stopped because we had a query issue kill both mirrors. For cost tradeoffs we typically only run two mirrors.

> To be more concrete, consider mirror 1 with 6 instances in the ASG and mirror 2 with 5 instances ...

As mentioned we currently just have one active mirror at a time and can quickly fail over to the other. In the past when we have tried it the configurations usually were one of:

1. Instance level, each mirror ASG needs to be the same size so that corresponding slots in each mirror have the same data. This is typically true regardless of policy. We experimented with round-robin, speculative execution, and corrective merges.
2. Mirror level, the sizes don't matter it just uses the final results from a given mirror.

**Comment by davecromberge** [comment]
Thanks for the your detailed and informative answer, it's good to know about the different considerations that went into your decision to settle on querying one mirror at a time.

I have settled on the same strategy, and use a somewhat rudimentary method to determine which mirror to use.  I have a client that subscribes to health check information from Consul, and it is accurate enough to determine the situation where an instance is down or restarts, thus losing all its metrics.  In such a case, the client will direct queries to the corresponding group, in a different mirror (which as you mentioned, should usually be in a different AZ). 

Initially I looked at Eureka, but from an operational perspective Consul allows for a cluster to form with minimal configuration on EC2, using tag metadata.   Also, it has the ability to discover services via DNS names.  From what I have read on the topic of comparing the two, Eureka seems to favour availability over consistency.

I have not load tested the above configuration at any kind of scale where availability becomes a critical factor, but I do aim aim to verify the mirror level short term storage strategy using a load testing tool.  Hopefully, in the process I will come back around to retest the situation I described in https://github.com/Netflix/atlas/issues/628 to determine if it's something to be concerned about, or whether I can close the issue.
