### ISSUE TITLE
Support raw datapoint input for atlas-eval

### ISSUE THREAD

**Issue by ruchirj** [Netflix/atlas#798]
There is a growing use-case around running atlas stack language evaluation on timeseries data that does not reside in Atlas and may not even be reported from the on instance client. It would really benefit us to use the atlas-eval library in a mode where the input form is a Stream of DataPoint messages, where DataPoint could look like `(ts: Long, value: Double, tags: Map[String, String])` 

This will help use cases targeted at alerting on streaming data, where users want to run some form of alerting but can't today, unless they store this data into Atlas. From an Atlas-Alerting perspective, this will help us on-board other time series data sources, while still adhering to the stack language as the DSL standard.

**Comment by pparth** [comment]
+1 This looks super useful to us too. 

@brharrington can you provide more information about how you use the atlas-eval lib in Netflix and whether it is too internal or can be used by OSS teams too?

**Comment by pparth** [comment]
@brharrington  Can you answer my question please?

**Comment by brharrington** [comment]
I think it should work fine for OSS teams, but there may be gaps I'm not aware of. Right now we have two main uses:

1. The alerting team uses the eval lib now to check most alerts against the internal deployment of the lwcapi providing the data. They also use it to render charts inline based on the stream if an alert triggers to provide the user with context.
2. The library is used in a [mantis](https://medium.com/netflix-techblog/stream-processing-with-mantis-78af913f51a6) source job allowing users of mantis to easily get Atlas data from lwcapi into their stream processing jobs. 

Most users outside of our specific team would interact with it via 2. So they don't use the library directly, but just consume from the source job. We prefer that because it allows us to control the upgrade cycle of the library without having to work with many teams.

There is also some discussion about building out a simple app we would run to allow users to configure a query and send to kafka. Still trying to understand the use-cases right now. This is already done by some users with their own simple job on mantis that reads from the source and outputs to kafka.
