### ISSUE TITLE
[Question] How can i see all the tags related to a metric?

### ISSUE THREAD

**Issue by kennedyoliveira** [Netflix/atlas#816]
Hello,

the tittle says pretty much all, for example, suppose i have a metric with name `http.server.request` how can i see all the related tags for this metric?

Thanks.

**Comment by brharrington** [comment]
You can query the [tags api](https://github.com/Netflix/atlas/wiki/Tags). To get the list of tag keys:

```
/api/v1/tags?q=name,http.server.request,:eq
```

Then you can call it with a particular tag key to get the list of values for that key:

```
/api/v1/tags/${key}?q=name,http.server.request,:eq
```

**Comment by kennedyoliveira** [comment]
Thank you @brharrington that worked! Another question regarding this approach, is it possible to get tags over a specific time? Because for example, there is one metric related to it, `instance-id` that represents a AWS instance, and then it return thousands of it, is it possible to get the tags related to the last 3 hours or 6 hours? 

I hope I expressed myself clear enough.

**Comment by brharrington** [comment]
Missed the follow up question, no it is not currently possible because of how the metadata is stored. The index used for querying tags doesn't have access to the data values over time, just a reference to the ids to lookup. This allows us to get a more compact index with contiguous time series over a longer time range. It is something we are considering in a future version, see #598.
