### ISSUE TITLE
How does compression work?

### ISSUE THREAD

**Issue by FlorianLautenschlager** [Netflix/atlas#826]
Hi there,

i wonder how the compression in memory works and if atlas sends compressed blocks to the storage component?

Thx,
Flo

**Comment by davecromberge** [comment]
Hi Florian, I'm not one of the Atlas developers, but when trying to find out more about the memory storage I made the following notes which could be useful in answering your question:

Block storage
-------------

Datapoints are encoded as 64-bit double precision values and stored in an
array, equal to the block size.

The memory database will assign each metric its own blockstore.  Metrics are
identified by their `ItemId` and associated with their block stores as follows:

```scala
    private val data = new ConcurrentHashMap[ItemId, BlockStore]
```

This data can be both read and written to concurrently, in a thread safe
manner.

Every blockstore consists of an array of N blocks of the following type:

 - Array Block
 - Float Array Block
 - Sparse Block
 - Constant Block
 - Rollup Block

Only the current block is mutable, any older data before the start of the
current block will violate a state invariant. Any newer data causes the current
block to complete, where it will be compressed into a new immutable block.

For each block, the start time is recorded as an epoch time in milliseconds.
 
## Array block (mutable)

Stores 64 bit double precision values in an array of size equal to block size,
where:

- Block size  = 3600 / step size e.g. 120 for 30 second step interval
- Block bytes = 4 + (block size * 8 bytes)
- Block store size = Number of blocks * block bytes

T0  | T1  | ... | Block size
--- | --- | --- | ---
D0  | D1  | ... | DN

## Float array block (immutable)

Identical to array blocks, except that values are stored in 32 bit single precision
floating point format. Array blocks are lossy-compressed to a float array block
when most of the values are discrete; and sparse blocks will yield no size
savings.
 
## Sparse block (immutable)

Stores a small set of discrete values, using a secondary indexes of single byte
pointers:

For example, consider the following array block of size 6:

T0  | T1  | T2  | T3  | T4  | T5
--- | --- | --- | --- | --- | ---
3.9 | 4.0 | 4.0 | 3.9 | 1.0 | 1.0

An index of single byte pointers to a value array will be created (identical
block size)

T0  | T1  | T2  | T3  | T4  | T5
--- | --- | --- | --- | --- | ---
P0  | P1  | P1  | P0  | P2  | P2

Value array:

P0  | P1  | P2
--- | --- | ---
3.9 | 4.0 | 1.0

Size of array block  = 6 * 8 bytes              = 48 bytes
Size of sparse block = 6 * 1 byte + 3 * 9 bytes = 33 bytes

For each array, an additional 4 bytes for the data structure is required.

## Constant block (immutable)

Simple block type of size 1 where all data points have the same value.

T0  |
--- |
D0  |

## Rollup block (mutable and immutable)

Consists of 4 identically sized blocks, which store the following aggregates:
- sum
- count
- min
- max

When mutable, all aggregate blocks are array blocks.  After compression, the
aggregate blocks will be one of the immutable blocks described above.

Memory consumption
----------------------

The memory growth of an Atlas instance determines how many distinct metrics can occupy a single instance.

Assumptions used in order to predict memory requirements:

- Memory consumption grows linearly with the number of distinct metrics stored
- Each metric key is unique and occupies the maximum number of permitted bytes, by default 40
- Each value is unique and occupies the maximum number of permitted bytes, by default 80
- The number of keys |keys| and values |values| per metric is the maximum number of permitted tags, by default 20
- Every data point is encoded as an 64-bit double (size = 8 bytes)
- All other costs are seen as overhead, and are accounted for by adding some reasonable #kB to the overall calculation.

Method
------

A load test was created that simulates samples arriving at regular intervals, filling blocks within the database in a predictable manner.
This test was performed against an empty Atlas instance, and heap dumps were captured and analyzed using the Eclipse Memory Analyzer Tool (MAT).
Visual VM and MAT only appear to show retained heap sizes for dominators of the heap - in this case the `data` of the MemoryDatabase and the `index` of the MemoryDatabase.  The index size should remain constant for the entire block store lifespan, but the data should grow by the same size for each new block (see `sizeOf` in Block module).

In order to get deep heap sizes, some minor modifications were made to the Atlas code base to make private members within MemoryDatabase visible. Also, some sizing calculations were added to the RoaringTagIndex to make the component cost more transparent.

A scala script was run in the console in order to calculate the cost of adding 6h of data for a new metric.


Calculation
-----------

The size of the values grows at a fixed rate, assuming that data is not compressed:

((block size * 8) + 4) * num blocks 

That is:

400 bytes for LTS rollup array with 5 min step interval
960 bytes for STS array with 30s step interval

The following deep size measurements were taken against the RoaringTagIndex (all measurements are in bytes):

| Field       | 0 metrics | 1 metric | 2 metrics | 3 metrics |
| ----------- | --------: | -------: | --------: | --------: |
| all         | 96        | 144      | 144       | 152       |
| keys        | 16        | 2,304    | 4,536     | 6,768     |
| values      | 16        | 2,416    | 4,808     | 7,208     |
| keyMap      | 96        | 2,624    | 5,072     | 7,696     |
| valueMap    | 96        | 2,736    | 5,344     | 8,128     |
| itemIds     | 16        | 88       | 152       | 224       |
| itemIndex   | 208       | 6,880    | 13,472    | 20,464    |
| keyIndex    | 208       | 3,232    | 6,224     | 9,616     |
| tagIndex    | 16        | 168      | 320       | 472       |
| itemTags    | 16        | 440      | 856       | 1,280     |
| Total       | 784       | 21,032   | 40,928    | 62,008    |

Deltas (bytes):

| Category     | 0 metrics | 1 metric | 2 metrics | 3 metrics |
| -----------: | --------: | -------: | --------: | --------: |
| index        | n/a       | 20,248   | 19896     | 21080     |
| block stores | n/a       | 6,144    | 6,144     | 6,144     |

The table above demonstrates a ~30Kb increase in size for each new STS metric with corresponding 6 hour block.
For LTS, the block stores would grow at rougly 2,784Kb per metric to result in a ~27Kb storage cost.
The cost of indexing metrics is the same regardless of LTS or STS.

Limitations
-----------

String interning and the effects of the GC make predicting memory sizes difficult.

**Comment by brharrington** [comment]
Nice answer @davecromberge, thanks for taking the time.

> In order to get deep heap sizes, some minor modifications were made to the Atlas code base to make private members within MemoryDatabase visible. Also, some sizing calculations were added to the RoaringTagIndex to make the component cost more transparent.

Do you think these changes would be generally useful? If there are changes we can incorporate to make it easier to operate or understand I'm happy to take suggestions or PRs.

**Comment by davecromberge** [comment]
Thanks @brharrington, in practice I have seen compression reducing the memory growth down to numbers well below the estimate.  Also, we have had some success in using Facebook's gorilla compression format for long term storage data on disk.  When doing so, we try and keep the indexes hot in memory and use the disks for the raw data.

As a rule of thumb I think that strings account for most of the memory consumption, and allowing larger tag cardinality is more expensive.  We have found the default of 20 is a reasonable choice.

Returning to your question, I don't think that exposing those fields will be very useful, as I found the exercise quite tricky and perhaps inaccurate.  I would be interested if you have any estimate for memory cost / metric, given the defaults?

There have been a few small pain points around extensibility and providing those custom modules such as long term storage, and I would be happy to try and gather more detail as feedback.   It has been some time since we started using Atlas and would need to try recall the details.  In general, I have found that the [iep-atlas example project](https://github.com/Netflix-Skunkworks/iep-apps) is a good starting point for newcomers to learn how to setup and run an Atlas instance with custom modules attached.

In the past, I have tried and failed previously to build a TSDB in Erlang, and appreciate that it's a very difficult problem to solve.  We have found this project to be well maintained and approachable and a very good foundation for time series.  Thanks for your efforts and for open sourcing the  project!

Here is the scala script I used to measure memory consumption:

```scala

import com.netflix.atlas.core.db._
import com.netflix.atlas.core.model._
import com.netflix.spectator.api.DefaultRegistry
import com.netflix.spectator.api.ManualClock
import com.typesafe.config.ConfigFactory
import com.netflix.atlas.core.db.MemoryDatabase
import com.twitter.common.objectsize.ObjectSizeCalculator
import com.twitter.common.objectsize.ObjectSizeCalculator.MemoryLayoutSpecification

import collection.JavaConverters._
import scala.util.Try


object DeepCalculator {
    
  private lazy val memoryLayoutSpecification = new MemoryLayoutSpecification {
    override def getArrayHeaderSize = 16
    override def getObjectHeaderSize = 12
    override def getObjectPadding = 8
    override def getReferenceSize = 4
    override def getSuperclassFieldPadding = 4
  }
  
  private lazy val objectSizeCalculator = new ObjectSizeCalculator(memoryLayoutSpecification)
  
  def sizeOf(o: Object) =
    objectSizeCalculator.calculateObjectSize(o)   
}



object Db {

  private val clock = new ManualClock()
  private val registry = new DefaultRegistry(clock)

  val instance = new MemoryDatabase(
    registry,
    ConfigFactory.parseString("""
      |block-size = 120
      |num-blocks = 6
      |rebuild-frequency = 10s
      |test-mode = true
      |intern-while-building = true
    """.stripMargin)
  )
  
  def dbSize: Long =
    instance.roaringTagIndex.bytesSize
    
  def storeSize: Long = {
    val iter = instance.data.entrySet.iterator
    val memStores = iter.asScala.toArray.map(e => e.getValue.asInstanceOf[MemoryBlockStore])
    // memStores.foreach(println)
    val sizes = memStores.map(x => DeepCalculator.sizeOf(x))
    sizes.sum
  }
  
  def addData(tags: Map[String, String], values: Double*): Unit = {
    val step = 60000 // 60s
    val data = values.toList.zipWithIndex.map {
      case (v, i) =>
        clock.setWallTime(i * step)
        Datapoint(tags, i * step, v)
    }
    instance.update(data)
    instance.index.rebuildIndex()
  }
}



object Metric {
    
    private var idx = 0
    private val blockSize = 120
    private val blocks = 6
    private val nvalues = blocks * blockSize
    
    private def createDynamicTags(nodeId: String, metric: Int, dynamicTags: Int = 19): Map[String, String] = {        
        (0 until dynamicTags - 1).map { i =>
            val key   = s"$nodeId.metric.$metric.tag.$i.key"
            val value = s"$nodeId.metric.$metric.tag.$i.value"
            key -> value
        }.toMap
    }
    
    def create(i: Int) = {
        val nodeId = f"i-0000000000000000$i"
        val mname = s"$nodeId.metric.$i"
        Map("name" -> mname) ++ createDynamicTags(nodeId, i).toMap
    }
    
    def values(n: Int) =
        (1 to n).toArray.map(_.toDouble)
        
    def storeBlock() = {
        val initialDbSize = Db.dbSize
        val initialStoreSize = Db.storeSize
        val metric = create(idx)
        val vs = values(nvalues)
        Db.addData(metric, vs: _*)
        val afterDbSize = Db.dbSize
        val afterStoreSize = Db.storeSize
        
        println(s"Difference in index sizes: ${afterDbSize - initialDbSize}")
        println(s"Difference in store sizes: ${afterStoreSize - initialStoreSize}")
        idx += 1
    }
}

// 0
Metric.storeBlock()
// 1
Metric.storeBlock()
// 2
Metric.storeBlock()
// 3
Metric.storeBlock()
// etc
```
