### ISSUE TITLE
Normalization Should Not Expand Macros

### ISSUE THREAD

**Issue by copperlight** [Netflix/atlas#862]
When using the /api/v1/expr/normalize endpoint, macros will be expanded, which can double the length of the original expression. This also makes it harder to track normalization changes to expressions.

When using the normalize endpoint, the macros should be kept, so that the minimum amount of change is introduced to the expression.

**Comment by brharrington** [comment]
Normalization will not expand most operator macros. The one that was causing problems here is `:des-epic-signal` which is quite involved and would be difficult to support cleanly without expansion. Also that macro only exists for backwards compatibility with some legacy epic use-cases that have long since been deprecated. After discussing with @copperlight it was decided it isn't work the effort.
