### ISSUE TITLE
how use fetch api

### ISSUE THREAD

**Issue by starlight0405** [Netflix/atlas#999]
When I use fetch Api, I don't know how to use it, can somebody help me?
I use like this: 

`curl -XGET 'http://localhost:7101/api/v2/fetch?q=name,anwserToEverything,:eq,(,name,),:by'`

The response is this:
```
data: {"type":"info","message":"100.0% of data complete"}
data: {"type":"close","message":"operation complete"}
```

**Comment by brharrington** [comment]
I'm assuming you are running with the sample memory config and `publish-test.sh` is being used to send data.

Based on the response, it isn't matching any data, note that the metric name is misspelled (`
s/anwser/answer/`) in your example. Form a local run I did:

```
$ curl -s 'http://localhost:7101/api/v2/fetch?q=name,answerToEverything,:eq,(,name,),:by&s=e-5m'
data: {"type":"timeseries","id":"b16bd3e7143dae969a9b9051059d31fb4d01031f","query":"name,answerToEverything,:eq,:sum,(,name,),:by","groupByKeys":["name"],"label":"(name=answerToEverything)","tags":{"nf.node":"***","atlas.dstype":"gauge","name":"answerToEverything"},"start":1551364860000,"end":1551365160000,"step":60000,"data":{"type":"array","values":[42.0,42.0,42.0,42.0,42.0]}}

data: {"type":"close","message":"operation complete"}
```

Note, in general the docs around the fetch API are pretty sparse. We are working on revamping some of the docs (see [atlas-docs repo](https://github.com/Netflix/atlas-docs)) and moving off of github wiki due to some of its limitations. Fetch API docs are on the todo list, but I have a pretty big back log and it is a lower priority right now, so it will likely be a while.

**Comment by starlight0405** [comment]
Thank you @brharrington that worked! Looking forward to the new doc.
